/**
 * Extension catalogue PetfoodTN — chiens, chats, oiseaux, poissons, NAC,
 * personnalisé, innovant, toilettage, transport, litière.
 */
const catalogExpansionProducts = [
  // —— Chiens : laisses, harnais, colliers ——
  {
    _id: 'prd_dog_harness_1',
    name: 'Harnais anti-traction Chien M',
    price: 42,
    discount: 10,
    description: 'Harnais rembourré, répartition de la charge, clips métalliques. Promenade confortable.',
    stock: 28,
    animalType: 'dog',
    category: 'accessoires',
    tags: ['harnais', 'laisse', 'promenade', 'chien'],
    popularity: 86,
    rating_avg: 4.6,
    rating_count: 34,
    imageUrl: 'https://images.unsplash.com/photo-1587300003388-59208cc962cb?auto=format&fit=crop&w=900&q=80',
    icon: '🦮',
  },
  {
    _id: 'prd_dog_collar_1',
    name: 'Collier classique ajustable Chien',
    price: 18,
    discount: 0,
    description: 'Collier nylon résistant, boucle sécurisée, anneau pour médaille.',
    stock: 45,
    animalType: 'dog',
    category: 'accessoires',
    tags: ['collier', 'classique', 'chien'],
    popularity: 80,
    rating_avg: 4.4,
    rating_count: 22,
    imageUrl: 'https://images.unsplash.com/photo-1548199973-03cce0bbc87b?auto=format&fit=crop&w=900&q=80',
    icon: '🐕',
  },
  {
    _id: 'prd_dog_collar_gps_1',
    name: 'Collier GPS traceur Chien',
    price: 189,
    discount: 8,
    description: 'Traceur GPS temps réel, app mobile, alerte zone, autonomie 7 jours. Waterproof.',
    stock: 15,
    animalType: 'dog',
    category: 'iot',
    tags: ['collier', 'gps', 'traceur', 'iot', 'chien'],
    popularity: 90,
    rating_avg: 4.7,
    rating_count: 41,
    imageUrl: 'https://images.unsplash.com/photo-1601758228041-f3b2795255f1?auto=format&fit=crop&w=900&q=80',
    icon: '📍',
  },
  {
    _id: 'prd_dog_collar_led_1',
    name: 'Collier lumineux LED Chien',
    price: 26,
    discount: 5,
    description: 'Bande LED rechargeable USB, 3 modes, visible la nuit jusqu’à 300 m.',
    stock: 32,
    animalType: 'dog',
    category: 'accessoires',
    tags: ['collier', 'led', 'lumineux', 'securite', 'chien'],
    popularity: 78,
    rating_avg: 4.5,
    rating_count: 19,
    imageUrl: 'https://images.unsplash.com/photo-1544568100-847a948585b9?auto=format&fit=crop&w=900&q=80',
    icon: '💡',
  },
  {
    _id: 'prd_dog_medal_1',
    name: 'Médaille personnalisée gravée Chien',
    price: 15,
    discount: 0,
    description: 'Médaille acier inox gravée prénom + téléphone. Forme os ou rond.',
    stock: 60,
    animalType: 'dog',
    category: 'personnalise',
    tags: ['medaille', 'gravee', 'personnalise', 'chien'],
    popularity: 88,
    rating_avg: 4.8,
    rating_count: 55,
    imageUrl: 'https://images.unsplash.com/photo-1583337130417-3346a1be7dee?auto=format&fit=crop&w=900&q=80',
    icon: '🏅',
  },
  {
    _id: 'prd_dog_bed_1',
    name: 'Lit orthopédique Chien L',
    price: 95,
    discount: 12,
    description: 'Coussin mémoire de forme, housse lavable, bordures surélevées.',
    stock: 18,
    animalType: 'dog',
    category: 'niches',
    tags: ['lit', 'coussin', 'orthopedique', 'chien'],
    popularity: 84,
    rating_avg: 4.6,
    rating_count: 27,
    imageUrl: 'https://images.unsplash.com/photo-1548199973-03cce0bbc87b?auto=format&fit=crop&w=900&q=80',
    icon: '🛏️',
  },
  {
    _id: 'prd_dog_toy_ball_1',
    name: 'Balle caoutchouc indestructible',
    price: 14,
    discount: 0,
    description: 'Balle flottante ultra-résistante pour jeu et mâchouillage.',
    stock: 50,
    animalType: 'dog',
    category: 'jouets',
    tags: ['jouet', 'balle', 'macher', 'chien'],
    popularity: 85,
    rating_avg: 4.5,
    rating_count: 48,
    imageUrl: 'https://images.unsplash.com/photo-1530281700549-e82e7bf110d6?auto=format&fit=crop&w=900&q=80',
    icon: '🎾',
  },
  {
    _id: 'prd_dog_toy_rope_1',
    name: 'Corde à mâcher coton 40 cm',
    price: 12,
    discount: 0,
    description: 'Corde naturelle pour jeu de traction et hygiène dentaire.',
    stock: 55,
    animalType: 'dog',
    category: 'jouets',
    tags: ['jouet', 'corde', 'macher', 'chien'],
    popularity: 82,
    rating_avg: 4.4,
    rating_count: 36,
    imageUrl: 'https://images.unsplash.com/photo-1587300003388-59208cc962cb?auto=format&fit=crop&w=900&q=80',
    icon: '🪢',
  },
  {
    _id: 'prd_dog_bowl_1',
    name: 'Gamelle anti-glouton Chien',
    price: 22,
    discount: 5,
    description: 'Bol labyrinthe ralentit l’ingestion, antidérapant, inox.',
    stock: 40,
    animalType: 'dog',
    category: 'accessoires',
    tags: ['gamelle', 'anti-glouton', 'chien'],
    popularity: 87,
    rating_avg: 4.7,
    rating_count: 52,
    imageUrl: 'https://images.unsplash.com/photo-1589924691995-400dc9ecc119?auto=format&fit=crop&w=900&q=80',
    icon: '🥣',
  },
  {
    _id: 'prd_dog_fountain_1',
    name: 'Fontaine à eau Chien 2 L',
    price: 49,
    discount: 10,
    description: 'Fontaine filtrante silencieuse, flux continu, encourage l’hydratation.',
    stock: 22,
    animalType: 'dog',
    category: 'accessoires',
    tags: ['fontaine', 'eau', 'hydratation', 'chien'],
    popularity: 79,
    rating_avg: 4.5,
    rating_count: 21,
    imageUrl: 'https://images.unsplash.com/photo-1589924691995-400dc9ecc119?auto=format&fit=crop&w=900&q=80',
    icon: '💧',
  },
  {
    _id: 'prd_dog_shampoo_1',
    name: 'Shampoing chien hypoallergénique 250 ml',
    price: 19,
    discount: 0,
    description: 'Formule douce pH neutre, sans paraben, pour peaux sensibles.',
    stock: 38,
    animalType: 'dog',
    category: 'toilettage',
    tags: ['shampooing', 'toilettage', 'chien'],
    popularity: 81,
    rating_avg: 4.5,
    rating_count: 29,
    imageUrl: 'https://images.unsplash.com/photo-1585421514738-01798e348b17?auto=format&fit=crop&w=900&q=80',
    icon: '🧴',
  },
  {
    _id: 'prd_dog_brush_1',
    name: 'Brosse démêlante double face Chien',
    price: 16,
    discount: 0,
    description: 'Picots + poils doux, retire nœuds et poils morts.',
    stock: 42,
    animalType: 'dog',
    category: 'toilettage',
    tags: ['brosse', 'toilettage', 'chien'],
    popularity: 76,
    rating_avg: 4.4,
    rating_count: 18,
    imageUrl: 'https://images.unsplash.com/photo-1534361960057-19889db9621e?auto=format&fit=crop&w=900&q=80',
    icon: '🪥',
  },
  {
    _id: 'prd_dog_nail_1',
    name: 'Coupe-griffes sécurité Chien',
    price: 14,
    discount: 0,
    description: 'Lame acier, limiteur de coupe, poignée antidérapante.',
    stock: 35,
    animalType: 'dog',
    category: 'toilettage',
    tags: ['coupe-griffes', 'toilettage', 'chien'],
    popularity: 74,
    rating_avg: 4.3,
    rating_count: 15,
    imageUrl: 'https://images.unsplash.com/photo-1548199973-03cce0bbc87b?auto=format&fit=crop&w=900&q=80',
    icon: '✂️',
  },
  {
    _id: 'prd_dog_poop_1',
    name: 'Sacs à déjections compostables (120)',
    price: 11,
    discount: 0,
    description: 'Sacs biodégradables, distributeur inclus, parfum léger.',
    stock: 70,
    animalType: 'dog',
    category: 'hygiene',
    tags: ['sacs', 'dejections', 'hygiene', 'chien'],
    popularity: 83,
    rating_avg: 4.4,
    rating_count: 40,
    imageUrl: 'https://images.unsplash.com/photo-1585421514738-01798e348b17?auto=format&fit=crop&w=900&q=80',
    icon: '🗑️',
  },
  {
    _id: 'prd_dog_raincoat_1',
    name: 'Imperméable Chien taille M',
    price: 38,
    discount: 10,
    description: 'Capuche, bandes réfléchissantes, fermeture ventrale réglable.',
    stock: 20,
    animalType: 'dog',
    category: 'vetements',
    tags: ['impermeable', 'manteau', 'pluie', 'chien'],
    popularity: 72,
    rating_avg: 4.3,
    rating_count: 14,
    imageUrl: 'https://images.unsplash.com/photo-1544568100-847a948585b9?auto=format&fit=crop&w=900&q=80',
    icon: '🧥',
  },
  {
    _id: 'prd_dog_carrier_1',
    name: 'Cage de transport Chien M IATA',
    price: 129,
    discount: 8,
    description: 'Caisse homologuée voyage, aération, poignée et roulettes.',
    stock: 10,
    animalType: 'dog',
    category: 'transport',
    tags: ['cage', 'transport', 'voyage', 'chien'],
    popularity: 77,
    rating_avg: 4.5,
    rating_count: 16,
    imageUrl: 'https://images.unsplash.com/photo-1450778869180-41d0601e046e?auto=format&fit=crop&w=900&q=80',
    icon: '🧳',
  },
  {
    _id: 'prd_dog_antipara_1',
    name: 'Antiparasitaire spot-on Chien (3 pipettes)',
    price: 34,
    discount: 5,
    description: 'Protection puces et tiques 3 mois, usage externe.',
    stock: 30,
    animalType: 'dog',
    category: 'sante',
    tags: ['antiparasitaire', 'puces', 'tiques', 'chien'],
    popularity: 91,
    rating_avg: 4.6,
    rating_count: 60,
    imageUrl: 'https://images.unsplash.com/photo-1628009368231-7bb7cfcb0def?auto=format&fit=crop&w=900&q=80',
    icon: '💊',
  },

  // —— Chats ——
  {
    _id: 'prd_cat_scratch_1',
    name: 'Griffoir vertical sisal 70 cm',
    price: 35,
    discount: 8,
    description: 'Poteau sisal stable, base large, protège meubles.',
    stock: 25,
    animalType: 'cat',
    category: 'accessoires',
    tags: ['griffoir', 'sisal', 'chat'],
    popularity: 84,
    rating_avg: 4.5,
    rating_count: 33,
    imageUrl: 'https://images.unsplash.com/photo-1545249390-6bdfa286032f?auto=format&fit=crop&w=900&q=80',
    icon: '🪵',
  },
  {
    _id: 'prd_cat_collar_engraved_1',
    name: 'Collier gravé Chat + clochette',
    price: 17,
    discount: 0,
    description: 'Collier sécurité breakaway, plaque prénom gravée.',
    stock: 40,
    animalType: 'cat',
    category: 'personnalise',
    tags: ['collier', 'grave', 'personnalise', 'chat'],
    popularity: 82,
    rating_avg: 4.6,
    rating_count: 28,
    imageUrl: 'https://images.unsplash.com/photo-1514888286974-6c03e2ca1dba?auto=format&fit=crop&w=900&q=80',
    icon: '🐈',
  },
  {
    _id: 'prd_cat_medal_1',
    name: 'Médaille Chat prénom gravé',
    price: 12,
    discount: 0,
    description: 'Médaille légère aluminium, gravure laser prénom + tel.',
    stock: 55,
    animalType: 'cat',
    category: 'personnalise',
    tags: ['medaille', 'personnalise', 'chat'],
    popularity: 86,
    rating_avg: 4.7,
    rating_count: 44,
    imageUrl: 'https://images.unsplash.com/photo-1574158622682-e40e69881006?auto=format&fit=crop&w=900&q=80',
    icon: '🏅',
  },
  {
    _id: 'prd_cat_bowl_custom_1',
    name: 'Gamelle personnalisée Chat',
    price: 28,
    discount: 5,
    description: 'Gamelle céramique avec prénom peint à la main.',
    stock: 20,
    animalType: 'cat',
    category: 'personnalise',
    tags: ['gamelle', 'personnalise', 'chat'],
    popularity: 75,
    rating_avg: 4.5,
    rating_count: 12,
    imageUrl: 'https://images.unsplash.com/photo-1589924691995-400dc9ecc119?auto=format&fit=crop&w=900&q=80',
    icon: '🥣',
  },
  {
    _id: 'prd_cat_mat_name_1',
    name: 'Tapis prénom Chat 40×60',
    price: 24,
    discount: 0,
    description: 'Tapis antidérapant brodé au prénom de votre chat.',
    stock: 22,
    animalType: 'cat',
    category: 'personnalise',
    tags: ['tapis', 'prenom', 'personnalise', 'chat'],
    popularity: 73,
    rating_avg: 4.4,
    rating_count: 10,
    imageUrl: 'https://images.unsplash.com/photo-1495360010541-f48722b34f7d?auto=format&fit=crop&w=900&q=80',
    icon: '🧵',
  },
  {
    _id: 'prd_pet_portrait_1',
    name: 'Portrait personnalisé animal (digital)',
    price: 45,
    discount: 10,
    description: 'Portrait illustré à partir de votre photo — fichier HD imprimable.',
    stock: 100,
    animalType: 'other',
    category: 'personnalise',
    tags: ['portrait', 'personnalise', 'cadeau'],
    popularity: 80,
    rating_avg: 4.9,
    rating_count: 25,
    imageUrl: 'https://images.unsplash.com/photo-1514888286974-6c03e2ca1dba?auto=format&fit=crop&w=900&q=80',
    icon: '🖼️',
  },
  {
    _id: 'prd_pet_giftbox_1',
    name: 'Boîte cadeau animaux surprise',
    price: 59,
    discount: 8,
    description: 'Coffret : friandises, jouet, médaille et carte personnalisée.',
    stock: 25,
    animalType: 'other',
    category: 'packs',
    tags: ['cadeau', 'box', 'personnalise', 'coffret', 'pack'],
    popularity: 85,
    rating_avg: 4.7,
    rating_count: 30,
    imageUrl: 'https://images.unsplash.com/photo-1601758228041-f3b2795255f1?auto=format&fit=crop&w=900&q=80',
    icon: '🎁',
  },
  {
    _id: 'prd_cat_litter_box_1',
    name: 'Bac à litière couvercle Chat',
    price: 42,
    discount: 10,
    description: 'Bac fermé anti-odeurs, porte battante, filtre charbon.',
    stock: 24,
    animalType: 'cat',
    category: 'litiere',
    tags: ['bac', 'litiere', 'chat'],
    popularity: 88,
    rating_avg: 4.5,
    rating_count: 47,
    imageUrl: 'https://images.unsplash.com/photo-1574158622682-e40e69881006?auto=format&fit=crop&w=900&q=80',
    icon: '🚽',
  },
  {
    _id: 'prd_cat_litter_1',
    name: 'Litière agglomérante 10 L',
    price: 18,
    discount: 5,
    description: 'Litière bentonite ultra-absorbante, contrôle odeurs 7 jours.',
    stock: 60,
    animalType: 'cat',
    category: 'litiere',
    tags: ['litiere', 'agglomerante', 'chat'],
    popularity: 94,
    rating_avg: 4.6,
    rating_count: 88,
    imageUrl: 'https://images.unsplash.com/photo-1514888286974-6c03e2ca1dba?auto=format&fit=crop&w=900&q=80',
    icon: '📦',
  },
  {
    _id: 'prd_cat_litter_scoop_1',
    name: 'Pelle à litière fine maille',
    price: 8,
    discount: 0,
    description: 'Pelle ergonomique, maille fine, crochet de rangement.',
    stock: 50,
    animalType: 'cat',
    category: 'litiere',
    tags: ['pelle', 'litiere', 'chat'],
    popularity: 70,
    rating_avg: 4.2,
    rating_count: 20,
    imageUrl: 'https://images.unsplash.com/photo-1585421514738-01798e348b17?auto=format&fit=crop&w=900&q=80',
    icon: '🥄',
  },
  {
    _id: 'prd_cat_toy_interactive_1',
    name: 'Jouet interactif laser auto Chat',
    price: 32,
    discount: 12,
    description: 'Projecteur laser automatique, 3 modes, timer sécurité.',
    stock: 28,
    animalType: 'cat',
    category: 'jouets',
    tags: ['jouet', 'interactif', 'laser', 'chat'],
    popularity: 86,
    rating_avg: 4.5,
    rating_count: 37,
    imageUrl: 'https://images.unsplash.com/photo-1495360010541-f48722b34f7d?auto=format&fit=crop&w=900&q=80',
    icon: '🕹️',
  },
  {
    _id: 'prd_cat_fountain_1',
    name: 'Fontaine à eau Chat 1,5 L',
    price: 39,
    discount: 8,
    description: 'Fontaine ultra-silencieuse, filtre triple, LED niveau d’eau.',
    stock: 26,
    animalType: 'cat',
    category: 'accessoires',
    tags: ['fontaine', 'eau', 'chat'],
    popularity: 89,
    rating_avg: 4.7,
    rating_count: 51,
    imageUrl: 'https://images.unsplash.com/photo-1589924691995-400dc9ecc119?auto=format&fit=crop&w=900&q=80',
    icon: '💧',
  },
  {
    _id: 'prd_cat_hammock_1',
    name: 'Hamac fenêtre Chat ventouses',
    price: 29,
    discount: 5,
    description: 'Hamac soleil pour fenêtre, ventouses renforcées, toile respirante.',
    stock: 20,
    animalType: 'cat',
    category: 'accessoires',
    tags: ['hamac', 'fenetre', 'chat'],
    popularity: 81,
    rating_avg: 4.4,
    rating_count: 23,
    imageUrl: 'https://images.unsplash.com/photo-1526336024174-e58f5cdd8e13?auto=format&fit=crop&w=900&q=80',
    icon: '🪟',
  },
  {
    _id: 'prd_cat_basket_1',
    name: 'Panier coussin Chat doux',
    price: 36,
    discount: 10,
    description: 'Panier rond molletonné, coussin amovible lavable.',
    stock: 22,
    animalType: 'cat',
    category: 'niches',
    tags: ['panier', 'coussin', 'chat'],
    popularity: 78,
    rating_avg: 4.5,
    rating_count: 19,
    imageUrl: 'https://images.unsplash.com/photo-1574158622682-e40e69881006?auto=format&fit=crop&w=900&q=80',
    icon: '🧺',
  },
  {
    _id: 'prd_cat_carrier_1',
    name: 'Sac de transport Chat souple',
    price: 45,
    discount: 8,
    description: 'Sac aéré, bandoulière, poche documents, compatible avion cabine.',
    stock: 18,
    animalType: 'cat',
    category: 'transport',
    tags: ['sac', 'transport', 'chat'],
    popularity: 80,
    rating_avg: 4.5,
    rating_count: 22,
    imageUrl: 'https://images.unsplash.com/photo-1450778869180-41d0601e046e?auto=format&fit=crop&w=900&q=80',
    icon: '👜',
  },
  {
    _id: 'prd_cat_brush_1',
    name: 'Brosse anti-poil Chat',
    price: 15,
    discount: 0,
    description: 'Brosse douce retire sous-poil, massage agréable.',
    stock: 40,
    animalType: 'cat',
    category: 'toilettage',
    tags: ['brosse', 'toilettage', 'chat'],
    popularity: 77,
    rating_avg: 4.4,
    rating_count: 26,
    imageUrl: 'https://images.unsplash.com/photo-1514888286974-6c03e2ca1dba?auto=format&fit=crop&w=900&q=80',
    icon: '🪥',
  },
  {
    _id: 'prd_cat_antipara_1',
    name: 'Antiparasitaire Chat (3 pipettes)',
    price: 28,
    discount: 5,
    description: 'Protection puces et tiques pour chats, application mensuelle.',
    stock: 35,
    animalType: 'cat',
    category: 'sante',
    tags: ['antiparasitaire', 'puces', 'chat'],
    popularity: 90,
    rating_avg: 4.6,
    rating_count: 54,
    imageUrl: 'https://images.unsplash.com/photo-1628009368231-7bb7cfcb0def?auto=format&fit=crop&w=900&q=80',
    icon: '💊',
  },

  // —— Innovants / IoT ——
  {
    _id: 'prd_iot_feeder_auto_1',
    name: 'Distributeur automatique croquettes',
    price: 159,
    discount: 10,
    description: 'Programmation app, portions grammes, caméra HD et micro.',
    stock: 14,
    animalType: 'other',
    category: 'iot',
    tags: ['distributeur', 'automatique', 'iot', 'feeder'],
    popularity: 92,
    rating_avg: 4.7,
    rating_count: 38,
    imageUrl: '/images/products/smart-feeder.svg',
    icon: '🤖',
  },
  {
    _id: 'prd_iot_camera_1',
    name: 'Caméra surveillance animaux 1080p',
    price: 99,
    discount: 12,
    description: 'Vision nuit, détection mouvement, audio bidirectionnel, cloud optionnel.',
    stock: 16,
    animalType: 'other',
    category: 'iot',
    tags: ['camera', 'surveillance', 'iot'],
    popularity: 88,
    rating_avg: 4.6,
    rating_count: 29,
    imageUrl: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?auto=format&fit=crop&w=900&q=80',
    icon: '📷',
  },
  {
    _id: 'prd_iot_water_disp_1',
    name: 'Distributeur d’eau automatique 3 L',
    price: 79,
    discount: 8,
    description: 'Réservoir XL, filtre charbon, alerte niveau bas Bluetooth.',
    stock: 18,
    animalType: 'other',
    category: 'iot',
    tags: ['eau', 'distributeur', 'automatique', 'iot'],
    popularity: 84,
    rating_avg: 4.5,
    rating_count: 20,
    imageUrl: 'https://images.unsplash.com/photo-1589924691995-400dc9ecc119?auto=format&fit=crop&w=900&q=80',
    icon: '🚰',
  },
  {
    _id: 'prd_iot_gps_tracker_1',
    name: 'Traceur GPS multi-animaux',
    price: 149,
    discount: 10,
    description: 'Clip collier universel, tracking live, historique trajets.',
    stock: 20,
    animalType: 'other',
    category: 'iot',
    tags: ['gps', 'traceur', 'iot'],
    popularity: 89,
    rating_avg: 4.6,
    rating_count: 33,
    imageUrl: 'https://images.unsplash.com/photo-1601758228041-f3b2795255f1?auto=format&fit=crop&w=900&q=80',
    icon: '📡',
  },
  {
    _id: 'prd_iot_smart_toy_1',
    name: 'Jouet intelligent app-contrôlé',
    price: 69,
    discount: 15,
    description: 'Robot jouet pilotable, modes auto, LED et sons.',
    stock: 15,
    animalType: 'other',
    category: 'iot',
    tags: ['jouet', 'intelligent', 'iot'],
    popularity: 81,
    rating_avg: 4.4,
    rating_count: 17,
    imageUrl: 'https://images.unsplash.com/photo-1530281700549-e82e7bf110d6?auto=format&fit=crop&w=900&q=80',
    icon: '🤖',
  },
  {
    _id: 'prd_iot_pet_door_1',
    name: 'Porte électronique animaux microchip',
    price: 189,
    discount: 8,
    description: 'Porte chatière lecture puce, verrouillage sélectif, installation mur/porte.',
    stock: 8,
    animalType: 'other',
    category: 'iot',
    tags: ['porte', 'electronique', 'microchip', 'iot'],
    popularity: 76,
    rating_avg: 4.5,
    rating_count: 11,
    imageUrl: 'https://images.unsplash.com/photo-1585421514738-01798e348b17?auto=format&fit=crop&w=900&q=80',
    icon: '🚪',
  },

  // —— Oiseaux ——
  {
    _id: 'prd_bird_cage_xl_1',
    name: 'Cage oiseaux XL double porte',
    price: 145,
    discount: 10,
    description: 'Cage spacieuse, plateaux amovibles, perchoirs inclus.',
    stock: 10,
    animalType: 'bird',
    category: 'niches',
    tags: ['cage', 'oiseau', 'habitat'],
    popularity: 78,
    rating_avg: 4.5,
    rating_count: 14,
    imageUrl: 'https://images.unsplash.com/photo-1552728089-57bdde30beb3?auto=format&fit=crop&w=900&q=80',
    icon: '🏠',
  },
  {
    _id: 'prd_bird_perch_1',
    name: 'Perchoirs naturels lot de 3',
    price: 18,
    discount: 0,
    description: 'Branches naturelles variées, fixation cage universelle.',
    stock: 35,
    animalType: 'bird',
    category: 'accessoires',
    tags: ['perchoir', 'oiseau'],
    popularity: 72,
    rating_avg: 4.3,
    rating_count: 12,
    imageUrl: 'https://images.unsplash.com/photo-1522926193341-e9ffd686c60f?auto=format&fit=crop&w=900&q=80',
    icon: '🪵',
  },
  {
    _id: 'prd_bird_nest_1',
    name: 'Nichoir intérieur oiseaux',
    price: 22,
    discount: 5,
    description: 'Nichoir bois pour perruches et canaris, ouverture sécurisée.',
    stock: 28,
    animalType: 'bird',
    category: 'niches',
    tags: ['nichoir', 'oiseau'],
    popularity: 70,
    rating_avg: 4.4,
    rating_count: 9,
    imageUrl: 'https://images.unsplash.com/photo-1444464666168-49d633b86797?auto=format&fit=crop&w=900&q=80',
    icon: '🪺',
  },
  {
    _id: 'prd_bird_toy_hang_1',
    name: 'Jouets suspendus oiseaux (kit 5)',
    price: 16,
    discount: 0,
    description: 'Miroirs, clochettes, échelles et anneaux à suspendre.',
    stock: 40,
    animalType: 'bird',
    category: 'jouets',
    tags: ['jouet', 'suspendu', 'oiseau'],
    popularity: 74,
    rating_avg: 4.3,
    rating_count: 15,
    imageUrl: 'https://images.unsplash.com/photo-1452570053594-1b985d6ea890?auto=format&fit=crop&w=900&q=80',
    icon: '🔔',
  },
  {
    _id: 'prd_bird_feeder_1',
    name: 'Mangeoire + abreuvoir oiseaux',
    price: 14,
    discount: 0,
    description: 'Duo mangeoire et abreuvoir anti-renversement pour cage.',
    stock: 45,
    animalType: 'bird',
    category: 'accessoires',
    tags: ['mangeoire', 'abreuvoir', 'oiseau'],
    popularity: 76,
    rating_avg: 4.4,
    rating_count: 18,
    imageUrl: 'https://images.unsplash.com/photo-1552728089-57bdde30beb3?auto=format&fit=crop&w=900&q=80',
    icon: '🥣',
  },
  {
    _id: 'prd_bird_bath_1',
    name: 'Baignoire oiseaux à fixer',
    price: 11,
    discount: 0,
    description: 'Baignoire transparente accroche porte cage, facile à remplir.',
    stock: 38,
    animalType: 'bird',
    category: 'accessoires',
    tags: ['baignoire', 'hygiene', 'oiseau'],
    popularity: 68,
    rating_avg: 4.2,
    rating_count: 8,
    imageUrl: 'https://images.unsplash.com/photo-1444464666168-49d633b86797?auto=format&fit=crop&w=900&q=80',
    icon: '🛁',
  },
  {
    _id: 'prd_bird_seeds_1',
    name: 'Mélange graines oiseaux 1 kg',
    price: 12,
    discount: 0,
    description: 'Mélange premium perruches, canaris et exotiques.',
    stock: 50,
    animalType: 'bird',
    category: 'nourriture',
    tags: ['graines', 'nourriture', 'oiseau'],
    popularity: 87,
    rating_avg: 4.5,
    rating_count: 42,
    imageUrl: 'https://images.unsplash.com/photo-1452570053594-1b985d6ea890?auto=format&fit=crop&w=900&q=80',
    icon: '🌾',
  },
  {
    _id: 'prd_bird_supplement_1',
    name: 'Complément vitaminé oiseaux',
    price: 15,
    discount: 0,
    description: 'Vitamines A/D/E en gouttes pour plumage et vitalité.',
    stock: 30,
    animalType: 'bird',
    category: 'sante',
    tags: ['complement', 'vitamines', 'oiseau'],
    popularity: 71,
    rating_avg: 4.3,
    rating_count: 11,
    imageUrl: 'https://images.unsplash.com/photo-1628009368231-7bb7cfcb0def?auto=format&fit=crop&w=900&q=80',
    icon: '💊',
  },
  {
    _id: 'prd_bird_clean_1',
    name: 'Kit nettoyage cage oiseaux',
    price: 13,
    discount: 0,
    description: 'Spray nettoyant + brosse + tapis fond jetables (30).',
    stock: 32,
    animalType: 'bird',
    category: 'hygiene',
    tags: ['nettoyage', 'cage', 'oiseau'],
    popularity: 69,
    rating_avg: 4.2,
    rating_count: 9,
    imageUrl: 'https://images.unsplash.com/photo-1585421514738-01798e348b17?auto=format&fit=crop&w=900&q=80',
    icon: '🧹',
  },

  // —— Poissons ——
  {
    _id: 'prd_fish_aqua_1',
    name: 'Aquarium starter 60 L LED',
    price: 189,
    discount: 10,
    description: 'Kit aquarium 60 L : filtre, éclairage LED, thermomètre.',
    stock: 8,
    animalType: 'fish',
    category: 'aquarium',
    tags: ['aquarium', 'kit', 'poisson'],
    popularity: 82,
    rating_avg: 4.6,
    rating_count: 15,
    imageUrl: 'https://images.unsplash.com/photo-1535591273668-578e31182c4f?auto=format&fit=crop&w=900&q=80',
    icon: '🐠',
  },
  {
    _id: 'prd_fish_filter_1',
    name: 'Filtre aquarium 200 L/h',
    price: 45,
    discount: 5,
    description: 'Filtre interne silencieux, media filtrant inclus.',
    stock: 20,
    animalType: 'fish',
    category: 'aquarium',
    tags: ['filtre', 'aquarium', 'poisson'],
    popularity: 75,
    rating_avg: 4.4,
    rating_count: 12,
    imageUrl: 'https://images.unsplash.com/photo-1535591273668-578e31182c4f?auto=format&fit=crop&w=900&q=80',
    icon: '⚙️',
  },
  {
    _id: 'prd_fish_heater_1',
    name: 'Chauffage aquarium 100 W',
    price: 28,
    discount: 0,
    description: 'Thermoplongeur précis, voyant LED, protection verre.',
    stock: 22,
    animalType: 'fish',
    category: 'aquarium',
    tags: ['chauffage', 'aquarium', 'poisson'],
    popularity: 74,
    rating_avg: 4.3,
    rating_count: 10,
    imageUrl: 'https://images.unsplash.com/photo-1535591273668-578e31182c4f?auto=format&fit=crop&w=900&q=80',
    icon: '🌡️',
  },
  {
    _id: 'prd_fish_air_1',
    name: 'Pompe à air aquarium silencieuse',
    price: 22,
    discount: 0,
    description: 'Pompe à air 2 sorties, tuyaux et diffuseurs inclus.',
    stock: 25,
    animalType: 'fish',
    category: 'aquarium',
    tags: ['pompe', 'air', 'aquarium'],
    popularity: 72,
    rating_avg: 4.3,
    rating_count: 11,
    imageUrl: 'https://images.unsplash.com/photo-1535591273668-578e31182c4f?auto=format&fit=crop&w=900&q=80',
    icon: '💨',
  },
  {
    _id: 'prd_fish_led_1',
    name: 'Éclairage LED aquarium clip',
    price: 35,
    discount: 8,
    description: 'Barre LED blanc/bleu, minuterie, clip universel.',
    stock: 18,
    animalType: 'fish',
    category: 'aquarium',
    tags: ['led', 'eclairage', 'aquarium'],
    popularity: 73,
    rating_avg: 4.4,
    rating_count: 9,
    imageUrl: 'https://images.unsplash.com/photo-1535591273668-578e31182c4f?auto=format&fit=crop&w=900&q=80',
    icon: '💡',
  },
  {
    _id: 'prd_fish_decor_1',
    name: 'Décor aquarium plantes + château',
    price: 27,
    discount: 5,
    description: 'Kit déco : plantes artificielles, rochers et château.',
    stock: 30,
    animalType: 'fish',
    category: 'aquarium',
    tags: ['decoration', 'plantes', 'aquarium'],
    popularity: 71,
    rating_avg: 4.2,
    rating_count: 14,
    imageUrl: 'https://images.unsplash.com/photo-1535591273668-578e31182c4f?auto=format&fit=crop&w=900&q=80',
    icon: '🏰',
  },
  {
    _id: 'prd_fish_food_1',
    name: 'Flocons poissons tropicaux 100 g',
    price: 9,
    discount: 0,
    description: 'Nourriture complète flocons, couleurs vives.',
    stock: 55,
    animalType: 'fish',
    category: 'nourriture',
    tags: ['nourriture', 'flocons', 'poisson'],
    popularity: 85,
    rating_avg: 4.5,
    rating_count: 36,
    imageUrl: 'https://images.unsplash.com/photo-1535591273668-578e31182c4f?auto=format&fit=crop&w=900&q=80',
    icon: '🐟',
  },
  {
    _id: 'prd_fish_water_1',
    name: 'Traitement eau aquarium 250 ml',
    price: 14,
    discount: 0,
    description: 'Conditionneur d’eau : chlore, métaux lourds, mucus protecteur.',
    stock: 40,
    animalType: 'fish',
    category: 'aquarium',
    tags: ['eau', 'traitement', 'aquarium'],
    popularity: 79,
    rating_avg: 4.4,
    rating_count: 21,
    imageUrl: 'https://images.unsplash.com/photo-1535591273668-578e31182c4f?auto=format&fit=crop&w=900&q=80',
    icon: '🧪',
  },

  // —— Lapins, hamsters, cochons d’Inde ——
  {
    _id: 'prd_nac_cage_1',
    name: 'Cage NAC 2 niveaux lapin/hamster',
    price: 89,
    discount: 10,
    description: 'Cage spacieuse, plateaux, roue et maisonnettes inclus.',
    stock: 12,
    animalType: 'rabbit',
    category: 'niches',
    tags: ['cage', 'nac', 'lapin', 'hamster'],
    popularity: 80,
    rating_avg: 4.5,
    rating_count: 16,
    imageUrl: 'https://images.unsplash.com/photo-1425082661705-1834bfd09dca?auto=format&fit=crop&w=900&q=80',
    icon: '🏠',
  },
  {
    _id: 'prd_nac_wheel_1',
    name: 'Roue d’exercice silencieuse 20 cm',
    price: 24,
    discount: 0,
    description: 'Roue sans axe bruyant, pour hamster et souris.',
    stock: 30,
    animalType: 'hamster',
    category: 'jouets',
    tags: ['roue', 'exercice', 'hamster'],
    popularity: 77,
    rating_avg: 4.4,
    rating_count: 19,
    imageUrl: 'https://images.unsplash.com/photo-1425082661705-1834bfd09dca?auto=format&fit=crop&w=900&q=80',
    icon: '🎡',
  },
  {
    _id: 'prd_nac_woodhouse_1',
    name: 'Maison en bois NAC',
    price: 19,
    discount: 5,
    description: 'Cabane bois non traité, cachette pour lapin ou cochon d’Inde.',
    stock: 28,
    animalType: 'rabbit',
    category: 'niches',
    tags: ['maison', 'bois', 'nac'],
    popularity: 75,
    rating_avg: 4.5,
    rating_count: 13,
    imageUrl: 'https://images.unsplash.com/photo-1425082661705-1834bfd09dca?auto=format&fit=crop&w=900&q=80',
    icon: '🪵',
  },
  {
    _id: 'prd_nac_tunnel_1',
    name: 'Tunnel tissu NAC 3 voies',
    price: 16,
    discount: 0,
    description: 'Tunnel pliable, lavable, exploration et cachette.',
    stock: 35,
    animalType: 'rabbit',
    category: 'jouets',
    tags: ['tunnel', 'jouet', 'nac'],
    popularity: 73,
    rating_avg: 4.3,
    rating_count: 11,
    imageUrl: 'https://images.unsplash.com/photo-1425082661705-1834bfd09dca?auto=format&fit=crop&w=900&q=80',
    icon: '🌀',
  },
  {
    _id: 'prd_nac_chew_1',
    name: 'Jouets à ronger bois (pack 6)',
    price: 12,
    discount: 0,
    description: 'Bâtons et cubes bois fruitier pour usure des dents.',
    stock: 45,
    animalType: 'rabbit',
    category: 'jouets',
    tags: ['ronger', 'dents', 'nac'],
    popularity: 78,
    rating_avg: 4.4,
    rating_count: 20,
    imageUrl: 'https://images.unsplash.com/photo-1425082661705-1834bfd09dca?auto=format&fit=crop&w=900&q=80',
    icon: '🦷',
  },
  {
    _id: 'prd_nac_bottle_1',
    name: 'Biberon abreuvoir NAC 250 ml',
    price: 9,
    discount: 0,
    description: 'Biberon anti-fuite à bille, fixation grillage.',
    stock: 50,
    animalType: 'rabbit',
    category: 'accessoires',
    tags: ['biberon', 'eau', 'nac'],
    popularity: 76,
    rating_avg: 4.3,
    rating_count: 17,
    imageUrl: 'https://images.unsplash.com/photo-1589924691995-400dc9ecc119?auto=format&fit=crop&w=900&q=80',
    icon: '🍼',
  },
  {
    _id: 'prd_nac_feeder_1',
    name: 'Mangeoire céramique NAC',
    price: 11,
    discount: 0,
    description: 'Bol lourd anti-renversement pour foin et granulés.',
    stock: 40,
    animalType: 'rabbit',
    category: 'accessoires',
    tags: ['mangeoire', 'nac'],
    popularity: 74,
    rating_avg: 4.4,
    rating_count: 14,
    imageUrl: 'https://images.unsplash.com/photo-1589924691995-400dc9ecc119?auto=format&fit=crop&w=900&q=80',
    icon: '🥣',
  },
  {
    _id: 'prd_nac_hay_1',
    name: 'Foin timothy premium 1 kg',
    price: 14,
    discount: 0,
    description: 'Foin riche en fibres pour lapins et cochons d’Inde.',
    stock: 40,
    animalType: 'rabbit',
    category: 'nourriture',
    tags: ['foin', 'nourriture', 'nac'],
    popularity: 86,
    rating_avg: 4.6,
    rating_count: 31,
    imageUrl: 'https://images.unsplash.com/photo-1425082661705-1834bfd09dca?auto=format&fit=crop&w=900&q=80',
    icon: '🌿',
  },
  {
    _id: 'prd_nac_litter_1',
    name: 'Litière copeaux NAC 5 L',
    price: 10,
    discount: 0,
    description: 'Copeaux de bois absorbants, poussière réduite.',
    stock: 48,
    animalType: 'rabbit',
    category: 'litiere',
    tags: ['litiere', 'copeaux', 'nac'],
    popularity: 81,
    rating_avg: 4.4,
    rating_count: 22,
    imageUrl: 'https://images.unsplash.com/photo-1425082661705-1834bfd09dca?auto=format&fit=crop&w=900&q=80',
    icon: '📦',
  },

  // —— Santé (catalogue + collab véto/vendeur) ——
  {
    _id: 'prd_health_vermifuge_1',
    name: 'Vermifuge chien comprimés (4 cps)',
    price: 22,
    discount: 0,
    description: 'Vermifuge large spectre pour chiens. Usage selon poids — conseil vétérinaire recommandé.',
    stock: 40,
    animalType: 'dog',
    category: 'sante',
    tags: ['sante', 'vermifuge', 'chien'],
    popularity: 88,
    rating_avg: 4.5,
    rating_count: 26,
    imageUrl: 'https://images.unsplash.com/photo-1628009368231-7bb7cfcb0def?auto=format&fit=crop&w=900&q=80',
    icon: '💊',
  },
  {
    _id: 'prd_health_vit_1',
    name: 'Vitamines multivitaminées animaux 60 cps',
    price: 19,
    discount: 5,
    description: 'Complément vitaminique A/B/D/E pour chien et chat.',
    stock: 45,
    animalType: 'other',
    category: 'sante',
    tags: ['sante', 'vitamine', 'complement'],
    popularity: 82,
    rating_avg: 4.4,
    rating_count: 18,
    imageUrl: 'https://images.unsplash.com/photo-1628009368231-7bb7cfcb0def?auto=format&fit=crop&w=900&q=80',
    icon: '💊',
  },
  {
    _id: 'prd_health_dental_1',
    name: 'Gel dentaire enzymatique 70 g',
    price: 16,
    discount: 0,
    description: 'Gel pour hygiène buccale, réduit le tartre. Chien et chat.',
    stock: 35,
    animalType: 'other',
    category: 'sante',
    tags: ['sante', 'dents', 'dentaire'],
    popularity: 79,
    rating_avg: 4.3,
    rating_count: 14,
    imageUrl: 'https://images.unsplash.com/photo-1583947215259-38e31be8751f?auto=format&fit=crop&w=900&q=80',
    icon: '🦷',
  },
  {
    _id: 'prd_health_disinfect_1',
    name: 'Désinfectant surfaces animaux 500 ml',
    price: 18,
    discount: 0,
    description: 'Désinfectant sans danger pour habitats et gamelles (rinçage recommandé).',
    stock: 30,
    animalType: 'other',
    category: 'sante',
    tags: ['sante', 'desinfectant', 'hygiene'],
    popularity: 76,
    rating_avg: 4.4,
    rating_count: 12,
    imageUrl: 'https://images.unsplash.com/photo-1585421514738-01798e348b17?auto=format&fit=crop&w=900&q=80',
    icon: '🧴',
  },
  {
    _id: 'prd_health_wipes_1',
    name: 'Lingettes nettoyantes santé (80 pcs)',
    price: 14,
    discount: 0,
    description: 'Lingettes antiseptiques douces pour pattes, plis et zones sensibles.',
    stock: 50,
    animalType: 'other',
    category: 'sante',
    tags: ['sante', 'lingettes', 'nettoyage'],
    popularity: 84,
    rating_avg: 4.5,
    rating_count: 28,
    imageUrl: 'https://images.unsplash.com/photo-1583947215259-38e31be8751f?auto=format&fit=crop&w=900&q=80',
    icon: '🧻',
  },
  {
    _id: 'prd_health_ear_eye_1',
    name: 'Lotion oreilles & yeux 100 ml',
    price: 21,
    discount: 5,
    description: 'Nettoyant doux pour conduits auditifs et contour des yeux. Chien/chat.',
    stock: 38,
    animalType: 'other',
    category: 'sante',
    tags: ['sante', 'oreilles', 'yeux', 'nettoyant'],
    popularity: 81,
    rating_avg: 4.5,
    rating_count: 20,
    imageUrl: 'https://images.unsplash.com/photo-1628009368231-7bb7cfcb0def?auto=format&fit=crop&w=900&q=80',
    icon: '👁️',
  },

  // —— Kits, packs & coffrets cadeaux ——
  {
    _id: 'prd_pack_puppy_1',
    name: 'Kit d’accueil pour chiot',
    price: 129,
    discount: 12,
    description:
      'Coffret démarrage chiot : croquettes découverte, gamelle anti-glouton, laisse + collier, jouet à mâcher, shampoing doux et guide d’accueil PetfoodTN.',
    stock: 20,
    animalType: 'dog',
    category: 'packs',
    tags: ['kit', 'accueil', 'chiot', 'pack', 'cadeau', 'coffret'],
    popularity: 93,
    rating_avg: 4.8,
    rating_count: 34,
    imageUrl: 'https://images.unsplash.com/photo-1544568100-847a948585b9?auto=format&fit=crop&w=900&q=80',
    icon: '🎁',
  },
  {
    _id: 'prd_pack_kitten_1',
    name: 'Kit d’accueil pour chaton',
    price: 119,
    discount: 10,
    description:
      'Coffret démarrage chaton : croquettes junior, gamelle, jouet interactif, griffoir mini, lingettes et guide d’accueil PetfoodTN.',
    stock: 22,
    animalType: 'cat',
    category: 'packs',
    tags: ['kit', 'accueil', 'chaton', 'pack', 'cadeau', 'coffret'],
    popularity: 92,
    rating_avg: 4.8,
    rating_count: 31,
    imageUrl: 'https://images.unsplash.com/photo-1574158622682-e40e69881006?auto=format&fit=crop&w=900&q=80',
    icon: '🎁',
  },
  {
    _id: 'prd_pack_grooming_1',
    name: 'Pack toilettage complet',
    price: 69,
    discount: 15,
    description:
      'Pack soin : shampoing, brosse démêlante, coupe-griffes, lingettes et serviette microfibre. Chien & chat.',
    stock: 28,
    animalType: 'other',
    category: 'packs',
    tags: ['pack', 'toilettage', 'soin', 'cadeau', 'coffret'],
    popularity: 87,
    rating_avg: 4.6,
    rating_count: 22,
    imageUrl: 'https://images.unsplash.com/photo-1585421514738-01798e348b17?auto=format&fit=crop&w=900&q=80',
    icon: '✂️',
  },
  {
    _id: 'prd_pack_travel_1',
    name: 'Pack voyage animal',
    price: 99,
    discount: 10,
    description:
      'Essentiels voyage : sac/caisse compacte, gamelle pliable, sacs déjections, collier LED et trousse premiers soins.',
    stock: 18,
    animalType: 'other',
    category: 'packs',
    tags: ['pack', 'voyage', 'transport', 'cadeau', 'coffret'],
    popularity: 85,
    rating_avg: 4.5,
    rating_count: 16,
    imageUrl: 'https://images.unsplash.com/photo-1450778869180-41d0601e046e?auto=format&fit=crop&w=900&q=80',
    icon: '🧳',
  },
  {
    _id: 'prd_pack_birthday_1',
    name: 'Pack anniversaire animal',
    price: 49,
    discount: 8,
    description:
      'Célébration : friandises premium, jouet surprise, médaille personnalisable et carte anniversaire PetfoodTN.',
    stock: 30,
    animalType: 'other',
    category: 'packs',
    tags: ['pack', 'anniversaire', 'cadeau', 'coffret', 'friandises'],
    popularity: 89,
    rating_avg: 4.7,
    rating_count: 27,
    imageUrl: 'https://images.unsplash.com/photo-1601758228041-f3b2795255f1?auto=format&fit=crop&w=900&q=80',
    icon: '🎂',
  },
  {
    _id: 'prd_pack_gift_premium_1',
    name: 'Coffret cadeau premium PetfoodTN',
    price: 89,
    discount: 12,
    description:
      'Coffret cadeau premium : friandises, accessoire surprise, portrait digital et emballage festif. Chien ou chat au choix.',
    stock: 25,
    animalType: 'other',
    category: 'packs',
    tags: ['coffret', 'cadeau', 'premium', 'pack', 'personnalise'],
    popularity: 91,
    rating_avg: 4.8,
    rating_count: 29,
    imageUrl: 'https://images.unsplash.com/photo-1514888286974-6c03e2ca1dba?auto=format&fit=crop&w=900&q=80',
    icon: '🎀',
  },
  {
    _id: 'prd_pack_gift_duo_1',
    name: 'Coffret cadeau duo maître & animal',
    price: 75,
    discount: 10,
    description:
      'Duo cadeau : mug PetfoodTN, friandises, petite couverture et carte message. Idéal offre familiale.',
    stock: 20,
    animalType: 'other',
    category: 'packs',
    tags: ['coffret', 'cadeau', 'duo', 'pack'],
    popularity: 84,
    rating_avg: 4.6,
    rating_count: 15,
    imageUrl: 'https://images.unsplash.com/photo-1543852786-1cf6624b9987?auto=format&fit=crop&w=900&q=80',
    icon: '🎁',
  },
];

module.exports = { catalogExpansionProducts };
